### ISSUE TITLE
Fix import inside opener.py to support python3

### ISSUE THREAD

**Issue by nofardi** [robhowley/s3-streaming#3]
Import inside opener.py should be:
`from urllib.parse import urlparse`
and not `from urlparse import urlparse`
since urlparse is not supported in python3

**Comment by robhowley** [comment]
thanks i'll put up a fix later today

**Comment by fjavieralba** [comment]
having the same problem, would be great if you update that import 🙂
thanks!

**Comment by robhowley** [comment]
that fix was already in but i realized i hadn't pushed it to pypi. sorry about that. should be there [now](https://pypi.org/project/s3-streaming/0.0.2/).

**Comment by fjavieralba** [comment]
thats great, thanks for the super quick response!
