### ISSUE TITLE
CSV deserializer: Iterator should return string

### ISSUE THREAD

**Issue by marcioemiranda** [robhowley/s3-streaming#6]
Hello,

If I configure the deserializer with the csv value, I get the following error:

> **iterator should return strings, not bytes (did you open the file in text mode?)**

The __iter__ method in FileLikeLineIterable returns bytes, and not strings, as expected by the csv module.

If I change it to the code bellow it works, but it may affect other parts of the code:

```
def __iter__(self):
        for next_chunk in self.wrapped_iterable:
            yield next_chunk.decode()
```

**Comment by robhowley** [comment]
thanks i'll look into it. appreciate your patience.

**Comment by robhowley** [comment]
should be ok thanks for your patience
